version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=host.docker.internal 
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=lumi_energy
    volumes:
      - .:/app
      - /app/node_modules
